# Generated by Django 6.0.7 on 2026-07-08 02:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PAYROLL', 'Payroll, Allowances & Benefits'), ('TRANSFER', 'Staff Rotations & Branch Postings'), ('LEAVE', 'Leave Requests & Absences'), ('PERFORMANCE', 'Performance Management & KPIs'), ('GRIEVANCE', 'Employee Grievances & Disciplinary'), ('MANPOWER', 'Branch Staffing Shortages / Recruitment')], max_length=25)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical / Urgent')], default='MEDIUM', max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed explanation of the branch engagement request')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted (Pending HRBP Assign)'), ('UNDER_REVIEW', 'Under Review by HRBP'), ('ESCALATED', 'Escalated to Head Office Specialist'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed / Finalized')], default='SUBMITTED', max_length=20)),
                ('is_confidential', models.BooleanField(default=False)),
                ('resolution_summary', models.TextField(blank=True, help_text='Final solution logged by the HRBP', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp used to calculate SLA turnaround metrics', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch Engagement',
                'verbose_name_plural': 'Branch Engagements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(help_text='e.g., Status changed to RESOLVED, Assigned HRBP changed', max_length=255)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
