# Generated by Django 6.0.7 on 2026-07-08 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchengagement',
            name='assigned_hrbp',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'hrbp'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchengagement',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementaudittrail',
            name='action_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementaudittrail',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='my_app.branchengagement'),
        ),
    ]
