
import os
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l9ab4+w+tnfi01tf3ci8tkn&o^^7_d7^ja5=vqn+)wx0pr(5lr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'my_app',
    'users',
    "rest_framework",
    "rest_framework_simplejwt",
    'rest_framework.authtoken', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Use custom user model from `users` app
AUTH_USER_MODEL = 'users.BankUser'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

JAZZMIN_SETTINGS = {
    'site_title': 'HR Engagement System',
    'site_header': 'HR Engagement System',
    'site_brand': 'HR Engagement System',
    'welcome_sign': 'Administrative Command Center',
    'site_logo': 'image/cente-removebg-preview.png',
    'site_logo_classes': 'img-circle elevation-3',
    'site_icon': 'fas fa-building',
    'copyright': 'HR Engagement System',
    'search_model': 'my_app.Employee',
    'user_avatar': None,
    'topmenu_links': [
        {'name': 'Dashboard', 'url': 'admin:index', 'permissions': ['auth.view_user']},
        {'name': 'Visit App Home', 'url': '/login', 'new_window': False},
    ],
    'usermenu_links': [
        {'name': 'View Site', 'url': '/login', 'new_window': False},
        {'model': 'users.bankuser'},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': [],
    'hide_models': [],
    'order_with_respect_to': [
        'my_app.Attendance',
        'my_app.Complaint',
        'my_app.LeaveRequest',
        'my_app.PerformanceReview',
        'my_app.Suggestion',
        'my_app.Employee',
        'my_app.EmployeeDocument',
        'my_app.JobTitle',
        'my_app.EmploymentType',
        'my_app.Branch',
        'my_app.Department',
        'my_app.Survey',
        'my_app.SurveyQuestion',
        'my_app.SurveyResponse',
        'my_app.Announcement',
        'my_app.Notification',
        'users.BankUser',
        'auth.Group',
        'my_app.AuditLog',
    ],
    'icons': {
        'my_app.Attendance': 'fas fa-calendar-check',
        'my_app.Complaint': 'fas fa-triangle-exclamation',
        'my_app.LeaveType': 'fas fa-layer-group',
        'my_app.LeaveRequest': 'fas fa-calendar-minus',
        'my_app.PerformanceReview': 'fas fa-chart-line',
        'my_app.Suggestion': 'fas fa-lightbulb',
        'my_app.Announcement': 'fas fa-bullhorn',
        'my_app.Notification': 'fas fa-bell',
        'my_app.Employee': 'fas fa-users',
        'my_app.EmployeeDocument': 'fas fa-folder-open',
        'my_app.JobTitle': 'fas fa-id-badge',
        'my_app.EmploymentType': 'fas fa-briefcase',
        'my_app.Branch': 'fas fa-code-branch',
        'my_app.Department': 'fas fa-sitemap',
        'my_app.Survey': 'fas fa-square-poll-horizontal',
        'my_app.SurveyQuestion': 'fas fa-circle-question',
        'my_app.SurveyResponse': 'fas fa-comments',
        'my_app.Recognition': 'fas fa-award',
        'users.BankUser': 'fas fa-user-shield',
        'auth.Group': 'fas fa-user-tag',
        'my_app.AuditLog': 'fas fa-shield-halved',
    },
    'default_icon_parents': 'fas fa-folder-tree',
    'related_modal_active': True,
    'show_ui_builder': False,
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-primary',
    'accent': 'accent-primary',
    'navbar': 'navbar-white navbar-light',
    'no_navbar_border': False,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'theme': 'default',
    'dark_mode_theme': 'cyborg',
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-outline-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}
